schema_version = 1
catalog = "catalog.toml"
structure_catalog = "../../../examples/workflows/pw_dft_scf/structures/catalog.toml"
simulation_catalog = "../../../examples/libraries/simulations/catalog.toml"
simulation_catalog_byte_size = 1502
simulation_catalog_sha256 = "16a52cdd077683e5d25cfa37568f4299b99861dd1a86f1c9b648ce03531f2ffa"
