from __future__ import annotations

import hashlib
import tempfile
import unittest
from pathlib import Path

from projectkoios.integrations.quantumespresso.pw2wannier90.artifacts import (  # noqa: E501
    QePw2Wannier90ArtifactDeclaration,
    QePw2Wannier90ArtifactInspector,
    QePw2Wannier90ArtifactRole,
)


class QePw2Wannier90ArtifactInspectorTest(unittest.TestCase):
    def test_verifies_required_and_accepted_optional_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            declarations = _write_artifacts(root, include_spn=True)

            observation = QePw2Wannier90ArtifactInspector().inspect(
                output_directory=root,
                seedname="silicon",
                producer_execution_record_sha256="e" * 64,
                declarations=declarations,
            )

            self.assertEqual(observation.band_count, 2)
            self.assertEqual(observation.kpoint_count, 2)
            self.assertEqual(observation.wannier_function_count, 1)
            self.assertEqual(observation.neighbor_count, 3)
            self.assertEqual(observation.eigenvalue_count, 4)

    def test_rejects_tampered_artifact(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            declarations = _write_artifacts(root)
            (root / "silicon.mmn").write_text("tampered\n", encoding="ascii")

            with self.assertRaisesRegex(ValueError, "size mismatch"):
                QePw2Wannier90ArtifactInspector().inspect(
                    output_directory=root,
                    seedname="silicon",
                    producer_execution_record_sha256="e" * 64,
                    declarations=declarations,
                )

    def test_rejects_dimension_disagreement(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            declarations = _write_artifacts(root, mmn_header="2 3 3")

            with self.assertRaisesRegex(ValueError, "dimensions disagree"):
                QePw2Wannier90ArtifactInspector().inspect(
                    output_directory=root,
                    seedname="silicon",
                    producer_execution_record_sha256="e" * 64,
                    declarations=declarations,
                )

    def test_rejects_incomplete_eigenvalue_grid(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            declarations = _write_artifacts(root, complete_eig=False)

            with self.assertRaisesRegex(ValueError, "complete band-by-k-point"):
                QePw2Wannier90ArtifactInspector().inspect(
                    output_directory=root,
                    seedname="silicon",
                    producer_execution_record_sha256="e" * 64,
                    declarations=declarations,
                )


def _write_artifacts(
    root: Path,
    *,
    mmn_header: str = "2 2 3",
    complete_eig: bool = True,
    include_spn: bool = False,
) -> tuple[QePw2Wannier90ArtifactDeclaration, ...]:
    payloads = {
        "silicon.amn": b"AMN generated by test\n2 2 1\n",
        "silicon.mmn": f"MMN generated by test\n{mmn_header}\n".encode("ascii"),
        "silicon.eig": (
            b"1 1 -1.0\n2 1 1.0\n1 2 -0.5\n2 2 1.5\n"
            if complete_eig
            else b"1 1 -1.0\n2 1 1.0\n1 2 -0.5\n"
        ),
    }
    if include_spn:
        payloads["silicon.spn"] = b"optional spin data\n"
    for filename, payload in payloads.items():
        (root / filename).write_bytes(payload)
    roles = {
        "silicon.amn": QePw2Wannier90ArtifactRole.amn,
        "silicon.mmn": QePw2Wannier90ArtifactRole.mmn,
        "silicon.eig": QePw2Wannier90ArtifactRole.eig,
        "silicon.spn": QePw2Wannier90ArtifactRole.spn,
    }
    return tuple(
        QePw2Wannier90ArtifactDeclaration(
            role=roles[filename],
            filename=filename,
            sha256=hashlib.sha256(payload).hexdigest(),
            byte_size=len(payload),
        )
        for filename, payload in payloads.items()
    )


if __name__ == "__main__":
    unittest.main()
